# Generated by Django 5.0.3 on 2024-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="name",
            field=models.CharField(verbose_name=255),
        ),
    ]
